slice_name: New installations vs new accounts
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 24__table
  viz_type: echarts_area
  x_axis: event_date
  time_grain_sqla: P1M
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  groupby:
  - event_type
  adhoc_filters:
  - expressionType: SIMPLE
    subject: event_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_4gvjmmn96zk_qovo6rshln
  - expressionType: SIMPLE
    subject: event_type
    operator: IN
    operatorId: IN
    comparator:
    - APP_INSTALLATION
    - ACCOUNT_CREATED
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_q7o13pm8uxb_crrss7vr0oa
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 11
query_context: '{"datasource":{"id":24,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"event_type","op":"IN","val":["APP_INSTALLATION","ACCOUNT_CREATED"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"event_date","label":"event_date","expressionType":"SQL"},"event_type"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10000,"series_columns":["event_type"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["event_date"],"columns":["event_type"],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"count":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"24__table","viz_type":"echarts_area","x_axis":"event_date","time_grain_sqla":"P1M","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":["count"],"groupby":["event_type"],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"event_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_4gvjmmn96zk_qovo6rshln"},{"expressionType":"SIMPLE","subject":"event_type","operator":"IN","operatorId":"IN","comparator":["APP_INSTALLATION","ACCOUNT_CREATED"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_q7o13pm8uxb_crrss7vr0oa"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[11],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d78a018d-7b21-4b1f-8126-2cfa7faf0658
version: 1.0.0
dataset_uuid: 4fa12cd9-94de-4ee0-8d27-f374463ee1d0
