slice_name: TX Value per City
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 24__table
  viz_type: pie
  groupby:
  - u_location
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: tx_price
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 771
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(tx_price)
    optionName: metric_yxw7i9w34t_6ibv6xkz4s9
  adhoc_filters:
  - expressionType: SIMPLE
    subject: event_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_56ttp7pdr6d_4h2xine2svk
  - expressionType: SIMPLE
    subject: event_type
    operator: ==
    operatorId: EQUALS
    comparator: TRANSACTION
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_m4ms740vdgp_5ue2crldw7y
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 11
query_context: '{"datasource":{"id":24,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"event_type","op":"==","val":"TRANSACTION"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["u_location"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"tx_price","description":null,"expression":null,"filterable":true,"groupby":true,"id":771,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(tx_price)","optionName":"metric_yxw7i9w34t_6ibv6xkz4s9"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"tx_price","description":null,"expression":null,"filterable":true,"groupby":true,"id":771,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(tx_price)","optionName":"metric_yxw7i9w34t_6ibv6xkz4s9"},false]],"annotation_layers":[],"row_limit":100,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"24__table","viz_type":"pie","groupby":["u_location"],"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"tx_price","description":null,"expression":null,"filterable":true,"groupby":true,"id":771,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(tx_price)","optionName":"metric_yxw7i9w34t_6ibv6xkz4s9"},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"event_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_56ttp7pdr6d_4h2xine2svk"},{"expressionType":"SIMPLE","subject":"event_type","operator":"==","operatorId":"EQUALS","comparator":"TRANSACTION","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_m4ms740vdgp_5ue2crldw7y"}],"row_limit":100,"sort_by_metric":true,"color_scheme":"supersetColors","show_labels_threshold":5,"show_legend":true,"legendType":"scroll","legendOrientation":"top","label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":70,"innerRadius":30,"extra_form_data":{},"dashboards":[11],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9f4f9002-3fea-4ad0-a39e-c90b615b548e
version: 1.0.0
dataset_uuid: 4fa12cd9-94de-4ee0-8d27-f374463ee1d0
